CREATE TYPE ProductList AS TABLE (ProductID INT NOT NULL)
CREATE TYPE IndividualList AS TABLE (IndividualID INT NOT NULL)
CREATE TYPE TablesList AS TABLE (TableID INT NOT NULL,
    NumberOfGuests INT NOT NULL)